### ISSUE TITLE
gdoc.png not found?

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#204]
When running I saw this in my terminal:

<pre>
home/overholt/Hasal/tests/test_firefox_gdoc_read_basic_table_1.sikuli ] stopped with error in line 15
[error] FindFailed ( can not find P(pics/gdoc.png) S: 0.85 in R[0,0 1920x1200]@S(0) )
[error] --- Traceback --- error source first
line: module ( function ) statement 
55: Region (  wait )   Line 2189, in file Region.java
20: gdoc (  wait_for_loaded )     wait(Pattern("pics/gdoc.png").similar(0.85))
[error] --- Traceback --- end --------------
</pre>

**Comment by ShakoHo** [comment]
Generally, it means the sikuli can't find Google doc icon on tab, we find that could happen in some environment... Could you try it again to see will it happen again?

**Comment by overholt** [comment]
Same thing a second time.

**Comment by overholt** [comment]
Third time, too. I see nothing in output/images/output (note: is the second 'output' a mistake?).

**Comment by ShakoHo** [comment]
Hi Andrew, 
It's not a mistake, it's normal condition.
And could you modify one value in your local environment.
Hasal/lib/sikuli/gdoc.sikuli/gdoc.py
Line 20:         wait(Pattern("pics/gdoc.png").similar(0.85))
Change to:         wait(Pattern("pics/gdoc.png").similar(0.5))
Then run the case again

**Comment by overholt** [comment]
After much pkill'ing everything a few times when focus got confused, I finally got it to run and did indeed end up with a *lot* of images in output/images/output :)

I don't understand the mechanisms at play here but if you're ok with it (seemingly often) not putting images into the output directory most of the time, feel free to close this issue.

Thanks!

**Comment by ShakoHo** [comment]
Hi Andrew,
I can explain about the modification a little bit more. We use the sikuli to simulate the user action, and the sikuli will use image matching to trigger the action, what you modify here is to recognize the gdoc load complete status, lower the similar value will let sikuli more easily to identify the icon, but with some risk of identify wrong icon. 
But in general, we found there will be some compatibility issue in different environment, and that's why we need to modify the value. 

And about another thing you mentioned, "not put images into the output directory", I'm not quite understand your point, could you explain more detail?  
In our framework, we will have a background video recording during testing, and at the end of test we will convert the video to images( store in output/images/output/case_name) and compare the sample images with these images to get the running time.

**Comment by overholt** [comment]
I see what you're saying now. It wasn't clear to me gdoc.png was something in the content we were looking for.

When things work I see images in output/images.
