### ISSUE TITLE
[meta] Composited Scrolling Benchmark

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#518]
@MikeLien had an experimental measure for frame rate during scrolling which worked nicely without APZ but could not compare Firefox and Chrome. Next step is evolving it to benchmark compositor based scrolling, which should include checkerboarding.

The following is mostly a braindump of all factors that make up scrolling that I am aware about and that would be important to consider. Hopefully it gets a deeper investigation and prototyping started.

All the metrics could be deferred to some degree from traces/profiles (Example Chrome for Frame Throughput [1]), but video would be more reliable.

Scrolling can be broken down into at least 3 distinct measures:

## ~1. Frame Throughput~

**Continued in #543**

FT can be broken down into two dimensions that describe the shape of dropped frames over the duration of scrolling

- Dropped frame duration or count
- Dropped frame ratio (`dropped frames / total frames`)

## ~2. Checkerboarding~

**Continued in #552**

Checkerboarding severity is an aggregated measure. One possible breakdown is laid out in [bug 1238040](https://bugzilla.mozilla.org/show_bug.cgi?id=1238040), landing new checkerboarding metrics.

Citing from the bug, each checkerboard event is described by:

- the peak checkerboard value
- the severity of the checkerboard
- the duration of the checkerboard in milliseconds

A whole scrolling session would also include the frequency of checkerboarding events.

## 3. Time from input to scroll start

Delay from scrolling input (`mousewheel` on desktop or `touchmove` on mobile) to first scrolled frame painted.

[1]: https://github.com/catapult-project/catapult/blob/7c8d6358a73d7d2feb3f0c08ca113e1acfa724f9/tracing/tracing/metrics/system_health/responsiveness_metric.html#L30

**Comment by digitarald** [comment]
This should align with https://bugzilla.mozilla.org/show_bug.cgi?id=1338347 .

One thought was that we could extract the aggregate for a test the browser profile's telemetry?

@MikeLien, what are your thoughts on this measure?

**Comment by MikeLien** [comment]
Based on the video analysis, the definition of frame per second (fps) might not the same as fps from compositor. Due to different screen recording settings from different platforms, i.e., currently `windows: 50 fps`, `ubuntu: 50 fps`, and `mac: 40 fps`, the results of video analysis could be taken as user perceived situation but might not totally align with compositor's results.

For the `Frame Throughput`, that's the indexes I proposed on Hawaii All Hands and it haven't integrated to current framework yet. The question here will be, what's the target case/web app we'd like to test after integration. From 15 topsites scrolling cases test, I couldn't find drop frame situation on the experiments before.

`Checkerboarding` indexes will be similar with `Frame Throughput` we originally defined or it could be treated as a subset of Frame Throughput, e.g., from current analysis, dropped frame duration might be the same as the duration of the checkerboard. Is this what we expected? From my opinion, I would like to transform original design to detect `Checkerboarding` and find another meticulous way to detect slightly jitter/jank. But this may need more time to achieve it. @digitarald what do you think?

The `Time from input to scroll start` would be a bottleneck from post-analysis without reference timestamps. Our strategy to analyze input latency/responsiveness could only raise screen recording's fps then detect and analyze the latency period between screen changes from continuously actions.

These indexes could be done from video analysis and some of them are already prototyping before.
I'm not quite sure what you mean about extract aggregate from browser profile's telemetry, does it mean we can auto collect these data in telemetry and hasal framework only need to extract them out?

**Comment by digitarald** [comment]
> Due to different screen recording settings from different platforms, i.e., currently windows: 50 fps, ubuntu: 50 fps, and mac: 40 fps, the results of video analysis could be taken as user perceived situation but might not totally align with compositor's results.

Can we run this test at 60 fps to have better coverage of dropped frames? As long as it synchronizes with vsync, we should be able to tell when a frame dropped.

> These indexes could be done from video analysis and some of them are already prototyping before.

Lets start with that then and see how far we get. So far scrolling/animation smoothness is the only performance category where we don't have any baseline against Chrome.

**Comment by MikeLien** [comment]
>> Due to different screen recording settings from different platforms, i.e., currently windows: 50 fps, ubuntu: 50 fps, and mac: 40 fps, the results of video analysis could be taken as user perceived situation but might not totally align with compositor's results.

> Can we run this test at 60 fps to have better coverage of dropped frames? As long as it synchronizes with vsync, we should be able to tell when a frame dropped.

We can configure such cases to see screen recording's highest fps can match 60 fps or not.

>> These indexes could be done from video analysis and some of them are already prototyping before.

> Lets start with that then and see how far we get. So far scrolling/animation smoothness is the only performance category where we don't have any baseline against Chrome.

We plan to integrate input latency measurement of typing first and the scrolling measurement will be the second one, would you like to exchange the priority?

**Comment by digitarald** [comment]
> We plan to integrate input latency measurement of typing first and the scrolling measurement will be the second one, would you like to exchange the priority?

@MikeLien both are the similar priority as we need to baseline against other browsers. If I need to make a call, prioritize input latency as you started on that already.

**Comment by MikeLien** [comment]
Sure, let's see how the first integrated case for input latency of typing will be.

**Comment by digitarald** [comment]
I will use this as tracking bug and file a separate issue for Frame Throughput specifically.

**Comment by bobbyc** [comment]
@MikeLien is it possible to modify #543 case to fulfill the following request?
>3. Time from input to scroll start
>
>Delay from scrolling input (mousewheel on desktop or touchmove on mobile) to first scrolled frame painted.

**Comment by MikeLien** [comment]
I think it's doable and this could leverage calculation method from input latency.

**Comment by bobbyc** [comment]
Closed issue as we done the MVPs.
