### ISSUE TITLE
Typing 100 characters test

### ISSUE THREAD

**Issue by digitarald** [Mozilla-TWQA/Hasal#653]
Creating an issue to keep track of discussions and test results. cc @MikeLien @onkeltom

Looks like we had a first run that measures time from first input to final paint. Problem is that this doesn't actually aggregate jank happening during the sequence. The measure is mostly made up by the input latency of the last frame. Jank during the sequence does not accumulate and only causes longer frames within the sequence with more typing coalesced into one paint.

Recommendation: Measure frame throughput for the sequence to get a distribution of frame lengths.

**Comment by MikeLien** [comment]
Sounds reasonable for issue hitting purpose and I have pilot run on sikuli directly on typing 400 chars and frame throughput measurement as well for one run. There has no obviously jank or longer long frame during typing actions.
@digitarald, do you think we still need to add these three typing 100 chars cases for facebook?
BTW, there has only one valuable result index from original frame thought design: `long frame`. Since there has average 10~30ms latency between each two characters, results from frame throughput will contain many noise information. If we decide to dive deeper into such case we need to modify the FT algorithm even create a new one to fulfill the needs.
@bobbyc thoughts?
