### ISSUE TITLE
Gecko profiler change to web extension break the original control mechanism in Hasal

### ISSUE THREAD

**Issue by ShakoHo** [Mozilla-TWQA/Hasal#686]

**Comment by overholt** [comment]
Can you describe the problem a bit more?

**Comment by ypwalter** [comment]
## 1. Background:
We used to use Geckoprofiler addon. We used an alternative way to install xpi by copying to destination xpi folder and add xpi's data into extension.json. Later on, we use websocket and hot keys to control in triggering, manipulating, and fetching of data.

## 2. Issue encountered:
### -  A different way to install the xpi:
The alternative way we used to install extension still works after some changes in program. However, after the alternative installation, it doesn't show up in browser but it does show that it's installed and enabled in add-on page. We might need to further figure things out.
### -  Default off(not started):
Even if we installed the extension properly, it is now default off. It used to started automatically if properly installed. We need to find out other ways for handling this.
### -  Websocket:
We injected a websocket to previous Geckoprofiler addon. In that case, we can get control of geckoprofiler. We can get share link and downloadables from Hasal framework. However, the websocket will not work for now and we need to rewrite or even create other tools so that we can still get stable data.

**Comment by overholt** [comment]
@squarewave or @mstange may have thoughts here. @squarewave did the work to convert the add-on to a web extension in https://github.com/devtools-html/Gecko-Profiler-Addon/pull/44
